// AUTO-GENERATED by tools/png_to_lvgl.py - do not edit.
#pragma once
#include <lvgl.h>

extern const lv_img_dsc_t rundeck_logo_18;
extern const lv_img_dsc_t rundeck_logo_32;
extern const lv_img_dsc_t rundeck_logo_80;
